# System performance tuning involves optimizing 
# hardware and software configurations to enhance efficiency, 
# responsiveness, and overall performance of computer systems.

# 1.Configure file descriptor limits

- name: "Configure file descriptor limits"
  copy:
    dest: /etc/security/limits.d/custom-limits.conf
    content: |
      * soft nofile {{ nofile_soft_limit }}
      * hard nofile {{ nofile_hard_limit }}
  notify: Reload limits

  # 2. Tune kernel parameters (sysctl)

- name: "Tune kernel parameters using sysctl"
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop: "{{ sysctl_params | dict2items }}"


# 3. Optimize boot time

- name: "Optimize boot time – mask unwanted services"
  systemd:
    name: "{{ item }}"
    masked: yes
  loop: "{{ disable_services }}"

# 4. Validate system resource usage

- name: "Validate system resource usage – file descriptors"
  shell: "ulimit -n"
  register: ulimit_output

