name: Golden Image Pipeline (Packer + Ansible - Azure)

on:
  push:
    branches: [ main, pipeline ]
  pull_request:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
  AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
jobs:

  #################################
  # 1. VALIDATION
  #################################
  validate:
    runs-on: ubuntu-latest
    name: Validate Packer & Ansible

    steps:
      - uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip

      - name: Packer Init
        run: packer init ubuntu-packer-test/

      - name: Packer Validate
    
        run: |
          packer validate -var "image_version=1.2.9" ubuntu-packer-test/




      - name: Ansible Lint
        run: |
          pip install ansible-lint
          ansible-lint ansible/playbook.yml