name: Golden Image Pipeline (Packer + Ansible - Azure)

on:
  push:
    branches: [ main, pipeline ]
  pull_request:

env:
  PACKER_VERSION: "1.9.2"
  IMAGE_VERSION: "1.2.${{ github.run_number }}"
  CLOUD_PROVIDER: "azure"
  OS_NAME: "ubuntu-22.04"
  AZURE_LOCATION: "eastus"
  ANSIBLE_FORCE_COLOR: "true"

jobs:

  #################################
  # 1. VALIDATION
  #################################
  validate:
    runs-on: ubuntu-latest
    name: Validate Packer & Ansible

    steps:
      - uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip

      - name: Packer Init
        run: packer init ubuntu-packer-test/

      - name: Packer Validate
        env:
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}
        run: |
          packer validate \
            -var "image_version=${IMAGE_VERSION}" \
            ubuntu-packer-test/


      - name: Ansible Lint
        run: |
          pip install ansible-lint
          ansible-lint ansible/